# Makefile for FORTRAN PROGRAM: FIZZ BUZZ
# author: Rebecca Yu (19778914)
# date: 14/08/2020

CC = f77
FILE = fizzbuzz.f
EXEC = fizzbuzz.exe

$(EXEC) : 
		$(CC) $(FILE) -o $(EXEC)

clean:
		rm -f $(EXEC)

run:
		./$(EXEC)