# Makefile for ALGOL PROGRAM: FIZZ BUZZ
# author: Rebecca Yu (19778914)
# date: 20/08/2020

CC = a68g
FILE = fizzbuzz.a68g
EXEC = fizzbuzz.so

$(EXEC) : 
		$(CC) -O $(FILE)

clean:
		rm -f $(EXEC)
